# Generated by Django 5.2.1 on 2025-05-20 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('water', 'Water'), ('chocolate', 'Chocolate'), ('flour', 'Flour'), ('other', 'Other')], max_length=100)),
                ('sampling_date', models.DateField()),
                ('sampling_operator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biosample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='biosamples.biosample')),
            ],
        ),
    ]
